2023-10-07 01:51:41,892 INFO [streaming_server.py:805] {'encoder': './sherpa-onnx-streaming-zipformer-en-2023-06-21/encoder-epoch-99-avg-1.int8.onnx', 'decoder': './sherpa-onnx-streaming-zipformer-en-2023-06-21/decoder-epoch-99-avg-1.int8.onnx', 'joiner': './sherpa-onnx-streaming-zipformer-en-2023-06-21/joiner-epoch-99-avg-1.int8.onnx', 'paraformer_encoder': None, 'paraformer_decoder': None, 'tokens': './sherpa-onnx-streaming-zipformer-en-2023-06-21/tokens.txt', 'sample_rate': 16000, 'feat_dim': 80, 'provider': 'cpu', 'decoding_method': 'greedy_search', 'num_active_paths': 4, 'use_endpoint': 1, 'rule1_min_trailing_silence': 2.4, 'rule2_min_trailing_silence': 1.2, 'rule3_min_utterance_length': 20, 'hotwords_file': '', 'hotwords_score': 1.5, 'port': 6006, 'nn_pool_size': 1, 'max_batch_size': 50, 'max_wait_ms': 10, 'max_message_size': 1048576, 'max_queue_size': 32, 'max_active_connections': 500, 'num_threads': 2, 'certificate': None, 'doc_root': 'web'}
2023-10-07 01:51:44,852 INFO [streaming_server.py:626] No certificate provided
2023-10-07 01:51:44,855 INFO [server.py:711] server listening on 0.0.0.0:6006
2023-10-07 01:51:44,864 INFO [server.py:711] server listening on [::]:6006
2023-10-07 01:51:44,864 INFO [streaming_server.py:652] Please visit one of the following addresses:

  http://localhost:6006

Since you are not providing a certificate, you cannot use your microphone from within the browser using public IP addresses. Only localhost can be used.You also cannot use 0.0.0.0 or 127.0.0.1
2023-10-07 01:52:07,150 INFO [server.py:233] connection failed (200 OK)
2023-10-07 01:52:07,151 INFO [server.py:268] connection closed
2023-10-07 01:52:07,242 INFO [server.py:233] connection failed (200 OK)
2023-10-07 01:52:07,244 INFO [server.py:233] connection failed (200 OK)
2023-10-07 01:52:07,245 INFO [server.py:268] connection closed
2023-10-07 01:52:07,245 INFO [server.py:268] connection closed
2023-10-07 01:52:07,246 INFO [server.py:233] connection failed (200 OK)
2023-10-07 01:52:07,246 INFO [server.py:233] connection failed (200 OK)
2023-10-07 01:52:07,247 INFO [server.py:233] connection failed (200 OK)
2023-10-07 01:52:07,247 INFO [server.py:268] connection closed
2023-10-07 01:52:07,247 INFO [server.py:268] connection closed
2023-10-07 01:52:07,247 INFO [server.py:268] connection closed
2023-10-07 01:52:07,304 INFO [server.py:233] connection failed (200 OK)
2023-10-07 01:52:07,304 INFO [server.py:268] connection closed
2023-10-07 01:52:07,434 INFO [server.py:233] connection failed (200 OK)
2023-10-07 01:52:07,436 INFO [server.py:233] connection failed (200 OK)
2023-10-07 01:52:07,442 INFO [server.py:233] connection failed (200 OK)
2023-10-07 01:52:07,443 INFO [server.py:268] connection closed
2023-10-07 01:52:07,443 INFO [server.py:268] connection closed
2023-10-07 01:52:07,444 INFO [server.py:268] connection closed
2023-10-07 01:52:11,223 INFO [server.py:646] connection open
2023-10-07 01:52:11,223 INFO [streaming_server.py:693] Connected: ('::1', 63374, 0, 0). Number of connections: 1/500
2023-10-07 01:52:15,848 INFO [streaming_server.py:677] Disconnected: ('::1', 63374, 0, 0). Number of connections: 0/500
2023-10-07 01:52:15,849 ERROR [server.py:242] connection handler failed
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websockets/legacy/server.py", line 240, in handler
    await self.ws_handler(self)
  File "/Users/fawazahamedshaik/github/ASR/Interactive_ASR/./streaming_server.py", line 670, in handle_connection
    await self.handle_connection_impl(socket)
  File "/Users/fawazahamedshaik/github/ASR/Interactive_ASR/./streaming_server.py", line 722, in handle_connection_impl
    voice(text)
  File "/Users/fawazahamedshaik/github/ASR/Interactive_ASR/./streaming_server.py", line 83, in voice
    output = tts.tts_to_file(text=text)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/TTS/api.py", line 391, in tts_to_file
    wav = self.tts(text=text, speaker=speaker, language=language, speaker_wav=speaker_wav, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/TTS/api.py", line 338, in tts
    wav = self.synthesizer.tts(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/TTS/utils/synthesizer.py", line 286, in tts
    raise ValueError(
ValueError: You need to define either `text` (for sythesis) or a `reference_wav` (for voice conversion) to use the Coqui TTS API.
2023-10-07 01:52:15,862 INFO [server.py:268] connection closed
