2023-10-07 14:41:51,899 INFO [streaming_server.py:805] {'encoder': './sherpa-onnx-streaming-zipformer-en-2023-06-21/encoder-epoch-99-avg-1.int8.onnx', 'decoder': './sherpa-onnx-streaming-zipformer-en-2023-06-21/decoder-epoch-99-avg-1.int8.onnx', 'joiner': './sherpa-onnx-streaming-zipformer-en-2023-06-21/joiner-epoch-99-avg-1.int8.onnx', 'paraformer_encoder': None, 'paraformer_decoder': None, 'tokens': './sherpa-onnx-streaming-zipformer-en-2023-06-21/tokens.txt', 'sample_rate': 16000, 'feat_dim': 80, 'provider': 'cpu', 'decoding_method': 'greedy_search', 'num_active_paths': 4, 'use_endpoint': 1, 'rule1_min_trailing_silence': 2.4, 'rule2_min_trailing_silence': 1.2, 'rule3_min_utterance_length': 20, 'hotwords_file': '', 'hotwords_score': 1.5, 'port': 6006, 'nn_pool_size': 1, 'max_batch_size': 50, 'max_wait_ms': 10, 'max_message_size': 1048576, 'max_queue_size': 32, 'max_active_connections': 500, 'num_threads': 2, 'certificate': None, 'doc_root': 'web'}
2023-10-07 14:41:53,886 INFO [streaming_server.py:625] No certificate provided
2023-10-07 14:41:53,887 INFO [server.py:711] server listening on [::]:6006
2023-10-07 14:41:53,888 INFO [server.py:711] server listening on 0.0.0.0:6006
2023-10-07 14:41:53,888 INFO [streaming_server.py:651] Please visit one of the following addresses:

  http://localhost:6006

Since you are not providing a certificate, you cannot use your microphone from within the browser using public IP addresses. Only localhost can be used.You also cannot use 0.0.0.0 or 127.0.0.1
2023-10-07 14:42:04,876 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:42:04,877 INFO [server.py:268] connection closed
2023-10-07 14:42:04,946 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:42:04,946 INFO [server.py:268] connection closed
2023-10-07 14:42:04,949 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:42:04,949 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:42:04,949 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:42:04,949 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:42:04,950 INFO [server.py:268] connection closed
2023-10-07 14:42:04,950 INFO [server.py:268] connection closed
2023-10-07 14:42:04,950 INFO [server.py:268] connection closed
2023-10-07 14:42:04,950 INFO [server.py:268] connection closed
2023-10-07 14:42:04,996 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:42:04,996 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:42:04,997 INFO [server.py:268] connection closed
2023-10-07 14:42:04,997 INFO [server.py:268] connection closed
2023-10-07 14:42:04,999 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:42:05,001 INFO [server.py:268] connection closed
2023-10-07 14:42:05,013 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:42:05,013 INFO [server.py:268] connection closed
2023-10-07 14:42:17,752 INFO [server.py:646] connection open
2023-10-07 14:42:17,753 INFO [streaming_server.py:692] Connected: ('::1', 60823, 0, 0). Number of connections: 1/500
2023-10-07 14:43:06,424 INFO [streaming_server.py:676] Disconnected: ('::1', 60823, 0, 0). Number of connections: 0/500
2023-10-07 14:43:06,424 ERROR [server.py:242] connection handler failed
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websockets/legacy/server.py", line 240, in handler
    await self.ws_handler(self)
  File "/Users/fawazahamedshaik/github/ASR/Interactive_ASR/./streaming_server.py", line 669, in handle_connection
    await self.handle_connection_impl(socket)
  File "/Users/fawazahamedshaik/github/ASR/Interactive_ASR/./streaming_server.py", line 744, in handle_connection_impl
    await socket.send(json.dumps(message))
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 935, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1005 (no status code [internal]); then sent 1005 (no status code [internal])
2023-10-07 14:43:06,430 INFO [server.py:268] connection closed
