2023-10-07 14:19:02,464 INFO [streaming_server.py:805] {'encoder': './sherpa-onnx-streaming-zipformer-en-2023-06-21/encoder-epoch-99-avg-1.int8.onnx', 'decoder': './sherpa-onnx-streaming-zipformer-en-2023-06-21/decoder-epoch-99-avg-1.int8.onnx', 'joiner': './sherpa-onnx-streaming-zipformer-en-2023-06-21/joiner-epoch-99-avg-1.int8.onnx', 'paraformer_encoder': None, 'paraformer_decoder': None, 'tokens': './sherpa-onnx-streaming-zipformer-en-2023-06-21/tokens.txt', 'sample_rate': 16000, 'feat_dim': 80, 'provider': 'cpu', 'decoding_method': 'greedy_search', 'num_active_paths': 4, 'use_endpoint': 1, 'rule1_min_trailing_silence': 2.4, 'rule2_min_trailing_silence': 1.2, 'rule3_min_utterance_length': 20, 'hotwords_file': '', 'hotwords_score': 1.5, 'port': 6006, 'nn_pool_size': 1, 'max_batch_size': 50, 'max_wait_ms': 10, 'max_message_size': 1048576, 'max_queue_size': 32, 'max_active_connections': 500, 'num_threads': 2, 'certificate': None, 'doc_root': 'web'}
2023-10-07 14:19:04,608 INFO [streaming_server.py:625] No certificate provided
2023-10-07 14:19:04,609 INFO [server.py:711] server listening on 0.0.0.0:6006
2023-10-07 14:19:04,610 INFO [server.py:711] server listening on [::]:6006
2023-10-07 14:19:04,611 INFO [streaming_server.py:651] Please visit one of the following addresses:

  http://localhost:6006

Since you are not providing a certificate, you cannot use your microphone from within the browser using public IP addresses. Only localhost can be used.You also cannot use 0.0.0.0 or 127.0.0.1
2023-10-07 14:19:54,995 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:19:54,996 INFO [server.py:268] connection closed
2023-10-07 14:19:55,047 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:19:55,053 INFO [server.py:268] connection closed
2023-10-07 14:19:55,054 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:19:55,054 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:19:55,056 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:19:55,057 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:19:55,057 INFO [server.py:268] connection closed
2023-10-07 14:19:55,057 INFO [server.py:268] connection closed
2023-10-07 14:19:55,058 INFO [server.py:268] connection closed
2023-10-07 14:19:55,058 INFO [server.py:268] connection closed
2023-10-07 14:19:55,096 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:19:55,096 INFO [server.py:268] connection closed
2023-10-07 14:19:55,100 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:19:55,101 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:19:55,101 INFO [server.py:268] connection closed
2023-10-07 14:19:55,101 INFO [server.py:268] connection closed
2023-10-07 14:19:55,193 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:19:55,193 INFO [server.py:268] connection closed
2023-10-07 14:20:05,084 INFO [server.py:646] connection open
2023-10-07 14:20:05,084 INFO [streaming_server.py:692] Connected: ('::1', 55241, 0, 0). Number of connections: 1/500
2023-10-07 14:21:39,202 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:21:39,234 INFO [server.py:268] connection closed
2023-10-07 14:21:41,323 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:21:41,325 INFO [streaming_server.py:676] Disconnected: ('::1', 55241, 0, 0). Number of connections: 0/500
2023-10-07 14:21:41,325 ERROR [server.py:242] connection handler failed
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websockets/legacy/server.py", line 240, in handler
    await self.ws_handler(self)
  File "/Users/fawazahamedshaik/github/ASR/Interactive_ASR/./streaming_server.py", line 669, in handle_connection
    await self.handle_connection_impl(socket)
  File "/Users/fawazahamedshaik/github/ASR/Interactive_ASR/./streaming_server.py", line 701, in handle_connection_impl
    samples = await self.recv_audio_samples(socket)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fawazahamedshaik/github/ASR/Interactive_ASR/./streaming_server.py", line 762, in recv_audio_samples
    message = await socket.recv()
              ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 935, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1001 (going away); then sent 1001 (going away)
2023-10-07 14:21:41,351 INFO [server.py:268] connection closed
2023-10-07 14:21:41,351 INFO [server.py:268] connection closed
2023-10-07 14:21:41,352 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:21:41,352 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:21:41,352 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:21:41,353 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:21:41,353 INFO [server.py:268] connection closed
2023-10-07 14:21:41,353 INFO [server.py:268] connection closed
2023-10-07 14:21:41,353 INFO [server.py:268] connection closed
2023-10-07 14:21:41,353 INFO [server.py:268] connection closed
2023-10-07 14:21:41,384 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:21:41,385 INFO [server.py:268] connection closed
2023-10-07 14:21:41,386 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:21:41,386 INFO [server.py:268] connection closed
2023-10-07 14:21:41,409 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:21:41,410 INFO [server.py:268] connection closed
2023-10-07 14:21:41,413 INFO [server.py:233] connection failed (200 OK)
2023-10-07 14:21:41,413 INFO [server.py:268] connection closed
2023-10-07 14:21:43,950 INFO [server.py:646] connection open
2023-10-07 14:21:43,951 INFO [streaming_server.py:692] Connected: ('::1', 55679, 0, 0). Number of connections: 1/500
